= AWS playground

This is a playground for me to mess around with AWS cloud services and also GitHub Actions. Since Terraform is boring, and HCL sucks, expect to see a lot of Pulumi, Nix, CUE and Golang junks here.

== OIDC authentication for CI/CD

AWS IAM Identity Center is used to authenticate the CI/CD workflow instead of static `+AWS_ACCESS_KEY_ID+` / `+AWS_SECRET_ACCESS_KEY+` values. See link:https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services[GitHub docs] for the detailed instruction.

== GitHub Actions

- link:https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions[aws-actions/configure-aws-credential] is used to authenticate the workflow.
- link:https://github.com/marketplace/actions/pulumi-cli-action[pulumi/actions] is used to setup and run pulumi commands.
- link:https://github.com/marketplace/actions/install-nix[cachix/install-nix-action] is used to install nix into the CI environment

== Manual resources

Because of the `+chicken & egg+` problem, some cloud resources are created beforehand to make the CI/CD work.

- Identity provider
- IAM role used for CI/CD of this project (with attached permission rule)
- S3 bucket to store the state of this Pulumi stack
- KMS key to encrypt Pulumi secrets

== Development

To get into a working development environment, run `+nix develop+`.

=== Tasks

Local tasks are managed by link:https://magefile.org[mage].

The GitHub workflow definitions are written in CUE inside link:./internal/ci[internal/ci/] directory. Run `+mage workflow:generate+` to validate and generate the result YAML files.

=== TODO

- [ ] Generate github-workflow schemas with Go library instead of invoking ad-hoc `+cue import+` command (so we can remove cue package from devShell)

== License

Apache 2.0
